In [1]:
import numpy as np
array = np.array([1, 2, 3, 4, 5], dtype=int)

print("Array:", array)
print("Boyut:", array.shape) 
print("Eleman sayısı:", array.size) 

Array: [1 2 3 4 5]
Boyut: (5,)
Eleman sayısı: 5


In [3]:
import numpy as np
array_2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print("İki Boyutlu Array:\n", array_2d)
print("Boyut:", array_2d.shape) 
print("Eleman sayısı:", array_2d.size) 
print("Satır sayısı:", array_2d.shape[0]) 
print("Sütun sayısı:", array_2d.shape[1]) 

print("1. satır, 2. sütun:", array_2d[0, 1])

print("Tüm satırlar, 1. sütun:", array_2d[:, 0])
print("1. satırın tüm elemanları:", array_2d[0, :]) 

İki Boyutlu Array:
 [[1 2 3]
 [4 5 6]]
Boyut: (2, 3)
Eleman sayısı: 6
Satır sayısı: 2
Sütun sayısı: 3
1. satır, 2. sütun: 2
Tüm satırlar, 1. sütun: [1 4]
1. satırın tüm elemanları: [1 2 3]


In [5]:
import numpy as np
array_1d = np.array([10, 20, 30, 40, 50], dtype=int)
print("Bir Boyutlu Array:", array_1d)
print("Index 2:", array_1d[2])
print("Dilimleme (1:4):", array_1d[1:4])

Bir Boyutlu Array: [10 20 30 40 50]
Index 2: 30
Dilimleme (1:4): [20 30 40]


In [7]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
print("\nİki Boyutlu Array:\n", array_2d)
print("1. satır, 2. sütun:", array_2d[0, 1])
print("Tüm satırlar, 1. sütun:", array_2d[:, 0])
print("1. satırın tüm elemanları:", array_2d[0, :])
print("1. ve 2. satır, 1. ve 2. sütunlar:\n", array_2d[0:2, 0:2])


İki Boyutlu Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1. satır, 2. sütun: 2
Tüm satırlar, 1. sütun: [1 4 7]
1. satırın tüm elemanları: [1 2 3]
1. ve 2. satır, 1. ve 2. sütunlar:
 [[1 2]
 [4 5]]


In [9]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=int)
print("\nÜç Boyutlu Array:\n", array_3d)
print("1. katman, 2. satır, 1. sütun:", array_3d[0, 1, 0]) 
print("Tüm katmanlar, 1. satır, tüm sütunlar:", array_3d[:, 0, :])
print("1. katmanın tüm satırları:\n", array_3d[0, :, :])
print("Tüm katmanlar, 1. sütun, 1. satır:\n", array_3d[:, 1, 0])


Üç Boyutlu Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1. katman, 2. satır, 1. sütun: 3
Tüm katmanlar, 1. satır, tüm sütunlar: [[1 2]
 [5 6]]
1. katmanın tüm satırları:
 [[1 2]
 [3 4]]
Tüm katmanlar, 1. sütun, 1. satır:
 [3 7]


In [11]:
import numpy as np
array_zeros = np.zeros((3, 3), dtype=int)
array_ones = np.ones((3, 3), dtype=int)
print("Sıfırlardan Oluşan Array:\n", array_zeros)
print("\nBirlerden Oluşan Array:\n", array_ones)

Sıfırlardan Oluşan Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Birlerden Oluşan Array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
array_combined_rows = np.vstack((array_zeros, array_ones))
print("\nSatır Bazında Birleştirilmiş Array:\n", array_combined_rows)
array_combined_cols = np.hstack((array_zeros, array_ones))
print("\nSütun Bazında Birleştirilmiş Array:\n", array_combined_cols)


Satır Bazında Birleştirilmiş Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sütun Bazında Birleştirilmiş Array:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
